export const ULDA_ERROR_CODES = Object.freeze({
  ULDA_FORMAT_SENTINEL: "ULDA_FORMAT_SENTINEL",
  ULDA_FORMAT_HEADER: "ULDA_FORMAT_HEADER",
  ULDA_FORMAT_SIZE: "ULDA_FORMAT_SIZE",
  ULDA_FORMAT_BODY_DIVISION: "ULDA_FORMAT_BODY_DIVISION",
  ULDA_FORMAT_UNKNOWN_MODE: "ULDA_FORMAT_UNKNOWN_MODE",
  ULDA_FORMAT_UNKNOWN_ALGORITHM: "ULDA_FORMAT_UNKNOWN_ALGORITHM",
  ULDA_HASHER_NOT_REGISTERED: "ULDA_HASHER_NOT_REGISTERED",
  ULDA_HASHER_OUTPUT_UNSUPPORTED: "ULDA_HASHER_OUTPUT_UNSUPPORTED",
  ULDA_HASHER_SIZE_MISMATCH: "ULDA_HASHER_SIZE_MISMATCH",
  ULDA_MODE_UNSUPPORTED: "ULDA_MODE_UNSUPPORTED",
  ULDA_MODE_EMPTY_BLOCKS: "ULDA_MODE_EMPTY_BLOCKS",
  ULDA_VERIFY_INCOMPATIBLE_PARAMS: "ULDA_VERIFY_INCOMPATIBLE_PARAMS",
  ULDA_VERIFY_INVALID_GAP: "ULDA_VERIFY_INVALID_GAP",
  ULDA_CONFIG_INVALID: "ULDA_CONFIG_INVALID",
  ULDA_RANDOM_UNAVAILABLE: "ULDA_RANDOM_UNAVAILABLE",
  ULDA_INTERNAL_ERROR: "ULDA_INTERNAL_ERROR"
});
